import { createTheme, THEME_GROUP_VSCODE } from "./helpers.js";

const noctisTheme = createTheme({
    id: "noctis",
    label: "Noctis",
    description: "Dark cyan-tinted palette with warm and cold medium contrast accents.",
    group: THEME_GROUP_VSCODE,
    page: {
        background: "#052529",
        foreground: "#b2cacd",
        overlayBackground: "#052529",
        overlayForeground: "#b2cacd",
        hintColor: "#40d4e7",
        modalBackdrop: "rgba(3, 25, 27, 0.72)",
        modalBackground: "#073940",
        modalBorder: "#0e6671",
        modalForeground: "#b2cacd",
        modalMuted: "#87a7ab",
        modalSelectedBackground: "#0b515b",
        modalSelectedBorder: "#40d4e7",
        modalSelectedForeground: "#ebfdff",
    },
    terminal: {
        background: "#03191b",
        foreground: "#b2cacd",
        cursor: "#85efff",
        cursorAccent: "#03191b",
        selectionBackground: "rgba(22, 159, 177, 0.27)",
        black: "#324a4d",
        red: "#e66533",
        green: "#49e9a6",
        yellow: "#e4b781",
        blue: "#49ace9",
        magenta: "#df769b",
        cyan: "#49d6e9",
        white: "#b2cacd",
        brightBlack: "#5e878c",
        brightRed: "#e97749",
        brightGreen: "#60ebb1",
        brightYellow: "#e69533",
        brightBlue: "#60b6eb",
        brightMagenta: "#e798b3",
        brightCyan: "#60dbeb",
        brightWhite: "#c1d4d7",
    },
    tui: {
        surface: "#03191b",
        activeHighlightBackground: "#083d44",
        activeHighlightForeground: "#ebfdff",
        selectionBackground: "#169fb1",
        selectionForeground: "#052529",
        promptCursorBackground: "#85efff",
        promptCursorForeground: "#03191b",
    },
});

export default noctisTheme;
