import { createTheme, THEME_GROUP_RETRO } from "./helpers.js";

const terminalGreenTheme = createTheme({
    id: "terminal-green",
    label: "Terminal Green",
    description: "Classic black terminal with phosphor green text, amber warnings, and crisp operator contrast.",
    group: THEME_GROUP_RETRO,
    page: {
        background: "#020503",
        foreground: "#c9f7d3",
        overlayBackground: "#020503",
        overlayForeground: "#d9ffe0",
        hintColor: "#7ee787",
        modalBackdrop: "rgba(0, 6, 2, 0.82)",
        modalBackground: "#061109",
        modalBorder: "#245c33",
        modalForeground: "#d9ffe0",
        modalMuted: "#83a98c",
        modalSelectedBackground: "#0b2a14",
        modalSelectedBorder: "#63e27a",
        modalSelectedForeground: "#ecfff0",
    },
    terminal: {
        background: "#020503",
        foreground: "#c9f7d3",
        cursor: "#8cff9f",
        cursorAccent: "#020503",
        selectionBackground: "#174923",
        black: "#061109",
        red: "#ff5f5f",
        green: "#63e27a",
        yellow: "#d6b95f",
        blue: "#5aa7ff",
        magenta: "#c586ff",
        cyan: "#5ce1d8",
        white: "#c9f7d3",
        brightBlack: "#5b7a61",
        brightRed: "#ff7f7f",
        brightGreen: "#8cff9f",
        brightYellow: "#f0d982",
        brightBlue: "#82bdff",
        brightMagenta: "#d9a8ff",
        brightCyan: "#89f4ee",
        brightWhite: "#effff1",
    },
    tui: {
        surface: "#020503",
        border: "#245c33",
        userChat: "#f0d982",
        userChatLabel: "#fff0a8",
        activeHighlightBackground: "#0b2a14",
        activeHighlightForeground: "#ecfff0",
        selectionBackground: "#63e27a",
        selectionForeground: "#020503",
        promptCursorBackground: "#8cff9f",
        promptCursorForeground: "#020503",
    },
});

export default terminalGreenTheme;