export const FOCUS_REGIONS = {
    SESSIONS: "sessions",
    CHAT: "chat",
    INSPECTOR: "inspector",
    ACTIVITY: "activity",
    PROMPT: "prompt",
    ADMIN: "admin",
};

export const INSPECTOR_TABS = ["sequence", "logs", "nodes", "history", "files", "stats"];

export const UI_COMMANDS = {
    REFRESH: "refresh",
    NEW_SESSION: "newSession",
    OPEN_MODEL_PICKER: "openModelPicker",
    OPEN_SWITCH_MODEL_PICKER: "openSwitchModelPicker",
    OPEN_THEME_PICKER: "openThemePicker",
    OPEN_RENAME_SESSION: "openRenameSession",
    OPEN_SESSION_FILTER: "openSessionFilter",
    OPEN_TERMINATE_PICKER: "openTerminatePicker",
    OPEN_MOVE_TO_GROUP: "openMoveToGroup",
    CREATE_SESSION_GROUP: "createSessionGroup",
    OPEN_ARTIFACT_UPLOAD: "openArtifactUpload",
    CLOSE_MODAL: "closeModal",
    MODAL_PREV: "modalPrev",
    MODAL_NEXT: "modalNext",
    MODAL_PANE_PREV: "modalPanePrev",
    MODAL_PANE_NEXT: "modalPaneNext",
    MODAL_CONFIRM: "modalConfirm",
    SEND_PROMPT: "sendPrompt",
    FOCUS_NEXT: "focusNext",
    FOCUS_PREV: "focusPrev",
    FOCUS_LEFT: "focusLeft",
    FOCUS_RIGHT: "focusRight",
    FOCUS_PROMPT: "focusPrompt",
    FOCUS_SESSIONS: "focusSessions",
    MOVE_SESSION_UP: "moveSessionUp",
    MOVE_SESSION_DOWN: "moveSessionDown",
    EXPAND_SESSION: "expandSession",
    COLLAPSE_SESSION: "collapseSession",
    NEXT_INSPECTOR_TAB: "nextInspectorTab",
    PREV_INSPECTOR_TAB: "prevInspectorTab",
    CYCLE_INSPECTOR_TAB: "cycleInspectorTab",
    GROW_LEFT_PANE: "growLeftPane",
    GROW_RIGHT_PANE: "growRightPane",
    GROW_SESSION_PANE: "growSessionPane",
    SHRINK_SESSION_PANE: "shrinkSessionPane",
    GROW_FOCUSED_PANE: "growFocusedPane",
    SHRINK_FOCUSED_PANE: "shrinkFocusedPane",
    OPEN_ARTIFACT_PICKER: "openArtifactPicker",
    OPEN_HELP: "openHelp",
    SEQUENCE_SELECT_PREV: "sequenceSelectPrev",
    SEQUENCE_SELECT_NEXT: "sequenceSelectNext",
    TOGGLE_SEQUENCE_TURN: "toggleSequenceTurn",
    TOGGLE_LOG_TAIL: "toggleLogTail",
    TOGGLE_STATS_VIEW: "toggleStatsView",
    OPEN_LOG_FILTER: "openLogFilter",
    OPEN_FILES_FILTER: "openFilesFilter",
    MOVE_FILE_UP: "moveFileUp",
    MOVE_FILE_DOWN: "moveFileDown",
    DOWNLOAD_SELECTED_FILE: "downloadSelectedFile",
    DELETE_SELECTED_FILE: "deleteSelectedFile",
    OPEN_SELECTED_FILE: "openSelectedFile",
    TOGGLE_FILE_PREVIEW_FULLSCREEN: "toggleFilePreviewFullscreen",
    TOGGLE_PANE_FULLSCREEN: "togglePaneFullscreen",
    SCROLL_UP: "scrollUp",
    SCROLL_DOWN: "scrollDown",
    PAGE_UP: "pageUp",
    PAGE_DOWN: "pageDown",
    EXPAND_HISTORY: "expandHistory",
    SCROLL_TOP: "scrollTop",
    SCROLL_BOTTOM: "scrollBottom",
    DONE_SESSION: "doneSession",
    CANCEL_SESSION: "cancelSession",
    STOP_TURN: "stopTurn",
    DELETE_SESSION: "deleteSession",
    REGENERATE_SESSION: "regenerateSession",
    PIN_SESSION: "pinSession",
    CYCLE_SESSION_VISIBILITY: "cycleSessionVisibility",
    OPEN_SHARE_SESSION: "openShareSession",
    TOGGLE_SELECT_MODE: "toggleSelectMode",
    TOGGLE_SESSION_SELECTION: "toggleSessionSelection",
    CLEAR_SESSION_SELECTION: "clearSessionSelection",
    OPEN_HISTORY_FORMAT: "openHistoryFormat",
    REFRESH_EXECUTION_HISTORY: "refreshExecutionHistory",
    EXPORT_EXECUTION_HISTORY: "exportExecutionHistory",
    // Admin Console — swaps out sessions+chat for the per-user admin view.
    OPEN_ADMIN_CONSOLE: "openAdminConsole",
    CLOSE_ADMIN_CONSOLE: "closeAdminConsole",
    OPEN_WORKSPACE: "openWorkspace",
    ADMIN_REFRESH_PROFILE: "adminRefreshProfile",
    ADMIN_SHOW_GHCP: "adminShowGhcp",
    ADMIN_SHOW_PACKAGES: "adminShowPackages",
    ADMIN_SHOW_WORKERS: "adminShowWorkers",
    ADMIN_WORKERS_REFRESH: "adminWorkersRefresh",
    ADMIN_PACKAGES_REFRESH: "adminPackagesRefresh",
    ADMIN_PACKAGES_NEXT: "adminPackagesNext",
    ADMIN_PACKAGES_PREV: "adminPackagesPrev",
    ADMIN_BEGIN_EDIT_GHCP_KEY: "adminBeginEditGhcpKey",
    ADMIN_CANCEL_EDIT_GHCP_KEY: "adminCancelEditGhcpKey",
    ADMIN_SAVE_GHCP_KEY: "adminSaveGhcpKey",
    ADMIN_CLEAR_GHCP_KEY: "adminClearGhcpKey",
};

export function cycleValue(values, current, delta) {
    const index = values.indexOf(current);
    const safeIndex = index === -1 ? 0 : index;
    const nextIndex = (safeIndex + delta + values.length) % values.length;
    return values[nextIndex];
}
