// @generated by packages/sdk/scripts/generate-web-client-ops.mjs — DO NOT EDIT.
// Regenerate: npm run generate:web-ops -w packages/sdk
//
// Derived from the protocol table (packages/sdk/api/src/protocol.js): the
// complete Web API operation surface, wire-shaped. Exposed by the web
// management client as `client.ops`. See contract test: web-client-op-coverage.

/** Every operation name in the protocol table, sorted. */
export const GENERATED_OP_NAMES: readonly string[] = [
    "adoptLegacySystemGitHubCopilotKey",
    "assignSessionsToGroup",
    "cancelPendingMessage",
    "cancelSession",
    "cancelSessionGroup",
    "clearProviderRoutingDependencies",
    "clearSystemSessionModel",
    "completeSession",
    "completeSessionGroup",
    "copyArtifact",
    "createMyProvider",
    "createProvider",
    "createSession",
    "createSessionForAgent",
    "createSessionGroup",
    "createSignalEndpoint",
    "createWebhookBinding",
    "createWebhookConnector",
    "createWebhookSessionTemplate",
    "deleteAgentPackage",
    "deleteArtifact",
    "deleteFact",
    "deleteGraphEdge",
    "deleteGraphNamespace",
    "deleteGraphNode",
    "deleteMyProvider",
    "deleteProvider",
    "deleteSession",
    "deleteSessionGroup",
    "downloadArtifact",
    "exportExecutionHistory",
    "factsCapabilities",
    "forcePurgeFacts",
    "getAgentPackage",
    "getAgentPackageFile",
    "getAgentPackageTree",
    "getArtifactMetadata",
    "getCanvasLive",
    "getCanvasShareLink",
    "getChildOutcome",
    "getClusterFeatureFlags",
    "getCurrentUserProfile",
    "getDefaultModel",
    "getDefaults",
    "getEmbedderStatus",
    "getExecutionHistory",
    "getFactsTombstoneStats",
    "getFleetGraphNodeUsage",
    "getFleetRetrievalUsage",
    "getFleetSkillUsage",
    "getFleetStats",
    "getGraphNamespace",
    "getLatestResponse",
    "getLegacyProviderMigrationStatus",
    "getLive",
    "getLogConfig",
    "getModelDefaults",
    "getModelsByProvider",
    "getMyFeatureFlags",
    "getOrchestrationStats",
    "getProviderStatus",
    "getProviderUsage",
    "getProviderUsageAgents",
    "getProviderUsageGrid",
    "getProviderUsageSummary",
    "getSession",
    "getSessionAccess",
    "getSessionCreationPolicy",
    "getSessionEvents",
    "getSessionEventsBefore",
    "getSessionFactsStats",
    "getSessionFootprint",
    "getSessionGraphEdgeSearchUsage",
    "getSessionGraphNodeUsage",
    "getSessionGraphSearches",
    "getSessionMetricSummary",
    "getSessionRetrievalUsage",
    "getSessionSignalState",
    "getSessionSkillUsage",
    "getSessionStatus",
    "getSessionTokensByModel",
    "getSessionTreeFactsStats",
    "getSessionTreeRetrievalUsage",
    "getSessionTreeSkillUsage",
    "getSessionTreeStats",
    "getSharedFactsStats",
    "getSystemGitHubCopilotKeyStatus",
    "getTopEventEmitters",
    "getUserFeatureFlags",
    "getUserStats",
    "getWebhookMetrics",
    "getWebhookReceipt",
    "getWorkerCount",
    "grantAgentPackageEditor",
    "grantSessionShare",
    "graphNeighbourhood",
    "graphStats",
    "listAgentPackageEditors",
    "listAgentPackages",
    "listAgentWorkerState",
    "listArtifacts",
    "listAuthzAudit",
    "listChildOutcomes",
    "listCreatableAgents",
    "listFeatureFlagChanges",
    "listFeatureFlags",
    "listFeatureFlagUsers",
    "listGraphNamespaces",
    "listKnownUsers",
    "listModels",
    "listPausedSessions",
    "listProviders",
    "listSessionGroups",
    "listSessions",
    "listSessionShares",
    "listSessionsPage",
    "listSignalEndpoints",
    "listWebhookBindings",
    "listWebhookConnectors",
    "listWebhookReceipts",
    "listWebhookSessionTemplates",
    "listWorkers",
    "moveSessionsToGroup",
    "pinAgentPackageVersion",
    "placeSessionsInGroup",
    "pruneDeletedSummaries",
    "raiseSignal",
    "readArtifactBase64",
    "readCanvasKv",
    "readFacts",
    "regenerateSession",
    "removeCanvasShareLink",
    "removeProviderLimit",
    "renameSession",
    "replayWebhookReceipt",
    "republishAgentPackageVersion",
    "resetCanvasShareLink",
    "resetClusterFeatureFlag",
    "restartSystemSession",
    "revokeAgentPackageEditor",
    "revokeSessionShare",
    "revokeSignalEndpoint",
    "revokeWebhookBinding",
    "revokeWebhookConnector",
    "revokeWebhookSessionTemplate",
    "searchFacts",
    "searchGraphEdges",
    "searchGraphNodes",
    "sendAnswer",
    "sendMessage",
    "sendSessionEvent",
    "setAgentPackageEnabled",
    "setAgentPackageScope",
    "setArtifactPinned",
    "setCanvasKvAccess",
    "setClusterDefault",
    "setClusterFeatureFlag",
    "setCurrentUserGitHubCopilotKey",
    "setCurrentUserProfileSettings",
    "setModelDefault",
    "setMyDefault",
    "setMyFeatureFlag",
    "setProviderAllowance",
    "setProviderHold",
    "setProviderLimit",
    "setProviderSystemUse",
    "setSessionModel",
    "setSessionVisibility",
    "setSystemGitHubCopilotKey",
    "setSystemModelDefault",
    "setSystemSessionModel",
    "setUserFeatureFlag",
    "similarFacts",
    "startFactsEmbedder",
    "stopFactsEmbedder",
    "stopSessionTurn",
    "storeFact",
    "testWebhookBinding",
    "unsetMyFeatureFlag",
    "unsetUserFeatureFlag",
    "updateMyProviderCredential",
    "updateSessionGroup",
    "updateSharedProviderCredential",
    "updateWebhookBinding",
    "updateWebhookConnector",
    "updateWebhookRetentionPolicy",
    "updateWebhookSessionTemplate",
    "uploadAgentPackage",
    "uploadArtifact",
    "upsertGraphEdge",
    "upsertGraphNamespace",
    "upsertGraphNode",
    "waitForStatusChange",
    "writeCanvasKv",
];

/**
 * The canonical Web API surface: one method per protocol-table operation.
 * Params are wire-shaped — exactly the fields the table declares for the
 * operation, flat. Path params are required; query/body params are optional
 * at the type level (the server validates).
 *
 * This is the layer that cannot drift: it is generated from the same table
 * the server generates its routes from.
 */
export interface ManagementOps {
    /**
     * Adopt the legacy synthetic System GHCP key into the calling admin's private, system-enabled provider. [admin]
     * @remarks `POST /management/providers/adopt-system-github-key` — access: `fleet:admin`
     */
    adoptLegacySystemGitHubCopilotKey(params: {
        name?: any;
    }): Promise<any>;

    /**
     * Deprecated alias of placeSessionsInGroup.
     * @remarks `POST /management/session-groups/:groupId/assign` — access: `authed`
     */
    assignSessionsToGroup(params: {
        groupId: string;
        sessionIds?: any;
    }): Promise<any>;

    /**
     * Cancel queued messages by client message ids.
     * @remarks `POST /sessions/:sessionId/cancel-pending` — access: `session:write`
     */
    cancelPendingMessage(params: {
        sessionId: string;
        clientMessageIds?: any;
    }): Promise<any>;

    /**
     * Cancel a session.
     * @remarks `POST /management/sessions/:sessionId/cancel` — access: `session:manage`
     */
    cancelSession(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Deprecated: Cancel all sessions in a group.
     * @remarks `POST /management/session-groups/:groupId/cancel` — access: `group:manage`
     */
    cancelSessionGroup(params: {
        groupId: string;
        reason?: any;
    }): Promise<any>;

    /**
     * Explicitly clear defaults and system-agent overrides that reference a provider. Shared providers require admin.
     * @remarks `POST /providers/:name/clear-routing` — access: `authed`
     */
    clearProviderRoutingDependencies(params: {
        name: string;
    }): Promise<any>;

    /**
     * Clear one persistent system-agent model override. [admin]
     * @remarks `DELETE /management/system-sessions/:agentId/model` — access: `fleet:admin`
     */
    clearSystemSessionModel(params: {
        agentId: string;
    }): Promise<any>;

    /**
     * Mark a session completed.
     * @remarks `POST /management/sessions/:sessionId/complete` — access: `session:manage`
     */
    completeSession(params: {
        sessionId: string;
        reason?: any;
    }): Promise<any>;

    /**
     * Deprecated: Complete all sessions in a group.
     * @remarks `POST /management/session-groups/:groupId/complete` — access: `group:manage`
     */
    completeSessionGroup(params: {
        groupId: string;
        options?: any;
    }): Promise<any>;

    /**
     * Copy an artifact across sessions (read access on the source, write on the target).
     * @remarks `POST /artifacts/copy` — access: `session:copy`
     */
    copyArtifact(params: {
        fromSessionId?: any;
        fromFilename?: any;
        toSessionId?: any;
        toFilename?: any;
    }): Promise<any>;

    /**
     * Create a provider of your own, on your own credentials. Nobody else sees it.
     * @remarks `POST /me/providers` — access: `authed`
     */
    createMyProvider(params: {
        name?: any;
        type?: any;
        credentials?: any;
        baseUrl?: any;
    }): Promise<any>;

    /**
     * Create a shared provider — one anyone may spend from. [admin]
     * @remarks `POST /management/providers` — access: `fleet:admin`
     */
    createProvider(params: {
        name?: any;
        type?: any;
        credentials?: any;
        baseUrl?: any;
    }): Promise<any>;

    /**
     * Create a session. Owner is the authenticated principal; visibility defaults to the deployment default.
     * @remarks `POST /sessions` — access: `session:create`
     */
    createSession(params: {
        model?: any;
        reasoningEffort?: any;
        contextTier?: any;
        groupId?: any;
        visibility?: any;
    }): Promise<any>;

    /**
     * Create a session bound to a named agent.
     * @remarks `POST /sessions/for-agent` — access: `session:create`
     */
    createSessionForAgent(params: {
        agentName?: any;
        model?: any;
        reasoningEffort?: any;
        contextTier?: any;
        title?: any;
        splash?: any;
        splashMobile?: any;
        initialPrompt?: any;
        groupId?: any;
        visibility?: any;
    }): Promise<any>;

    /**
     * Create a session group.
     * @remarks `POST /management/session-groups` — access: `authed`
     */
    createSessionGroup(params: {
        input?: any;
    }): Promise<any>;

    /**
     * Mint a fixed-target webhook capability. The token is returned once; expiry, use and rate limits are enforced durably.
     * @remarks `POST /sessions/:sessionId/signal-endpoints/:signalName` — access: `session:write`
     */
    createSignalEndpoint(params: {
        sessionId: string;
        signalName: string;
        options?: any;
    }): Promise<any>;

    /**
     * Bind an approved source/filter to one authorized action. Payloads cannot select destinations or session configuration.
     * @remarks `POST /webhooks/bindings` — access: `authed`
     */
    createWebhookBinding(params: {
        input?: any;
    }): Promise<any>;

    /**
     * Approve a GitHub or Azure DevOps source and authentication references. Never accepts plaintext secrets.
     * @remarks `POST /webhooks/connectors` — access: `fleet:admin`
     */
    createWebhookConnector(params: {
        input?: any;
    }): Promise<any>;

    /**
     * Approve a source-scoped session template with fixed owner, agent, namespace, model policy and prompt.
     * @remarks `POST /webhooks/templates` — access: `fleet:admin`
     */
    createWebhookSessionTemplate(params: {
        input?: any;
    }): Promise<any>;

    /**
     * Delete a package: every version and its artifacts. Creator or admin. Live sessions using its agents fail resolution on their next turn. `scope` picks which same-named copy.
     * @remarks `DELETE /agent-packages/:name` — access: `authed`
     */
    deleteAgentPackage(params: {
        name: string;
        scope?: string;
        ownerProvider?: string;
        ownerSubject?: string;
    }): Promise<any>;

    /**
     * Delete an artifact.
     * @remarks `DELETE /sessions/:sessionId/artifacts/:filename` — access: `session:manage`
     */
    deleteArtifact(params: {
        sessionId: string;
        filename: string;
    }): Promise<any>;

    /**
     * Delete a fact / pattern (DeleteFactInput). POST because DELETE bodies are unreliable.
     * @remarks `POST /facts/delete` — access: `facts:write`
     */
    deleteFact(params: {
        input?: any;
    }): Promise<any>;

    /**
     * Delete a graph edge.
     * @remarks `POST /graph/edges/delete` — access: `authed`
     */
    deleteGraphEdge(params: {
        fromKey?: any;
        toKey?: any;
        predicateKey?: any;
        namespace?: any;
    }): Promise<any>;

    /**
     * Delete a graph namespace and its data. [admin]
     * @remarks `DELETE /graph/namespaces/:namespace` — access: `fleet:admin` (admin)
     */
    deleteGraphNamespace(params: {
        namespace: string;
    }): Promise<any>;

    /**
     * Delete a graph node.
     * @remarks `POST /graph/nodes/delete` — access: `authed`
     */
    deleteGraphNode(params: {
        nodeKey?: any;
        namespace?: any;
    }): Promise<any>;

    /**
     * Remove one of your own providers. Returns how many sessions are now waiting on the name.
     * @remarks `DELETE /me/providers/:name` — access: `authed`
     */
    deleteMyProvider(params: {
        name: string;
    }): Promise<any>;

    /**
     * Remove a shared provider. Returns how many sessions are now waiting on the name. [admin]
     * @remarks `DELETE /management/providers/:name` — access: `fleet:admin`
     */
    deleteProvider(params: {
        name: string;
    }): Promise<any>;

    /**
     * Cancel and soft-delete a session.
     * @remarks `DELETE /sessions/:sessionId` — access: `session:destroy`
     */
    deleteSession(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Delete a session group. Clears the owner's placements; sessions are untouched.
     * @remarks `DELETE /management/session-groups/:groupId` — access: `group:manage`
     */
    deleteSessionGroup(params: {
        groupId: string;
    }): Promise<any>;

    /**
     * Artifact content as text (JSON envelope). Binary: GET …/download.
     * @remarks `GET /sessions/:sessionId/artifacts/:filename/text` — access: `session:read`
     */
    downloadArtifact(params: {
        sessionId: string;
        filename: string;
    }): Promise<any>;

    /**
     * Export execution history to an artifact; returns artifact meta.
     * @remarks `POST /management/sessions/:sessionId/export-execution-history` — access: `session:manage`
     */
    exportExecutionHistory(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Store capabilities: { search, embedder, graph } — the remote isEnhancedFactStore/isGraphStore.
     * @remarks `GET /facts/capabilities` — access: `authed`
     */
    factsCapabilities(params?: Record<string, never>): Promise<any>;

    /**
     * Force-purge soft-deleted facts (ForcePurgeFactsInput). [admin]
     * @remarks `POST /facts/purge` — access: `fleet:admin` (admin)
     */
    forcePurgeFacts(params: {
        input?: any;
    }): Promise<any>;

    /**
     * One package with its full version history. `scope` picks which same-named copy.
     * @remarks `GET /agent-packages/:name` — access: `authed`
     */
    getAgentPackage(params: {
        name: string;
        scope?: string;
        ownerProvider?: string;
        ownerSubject?: string;
    }): Promise<any>;

    /**
     * One file from the package tarball (preview; text size-capped, binary flagged).
     * @remarks `GET /agent-packages/:name/file` — access: `authed`
     */
    getAgentPackageFile(params: {
        name: string;
        semver?: string;
        filePath?: string;
        scope?: string;
        ownerProvider?: string;
        ownerSubject?: string;
    }): Promise<any>;

    /**
     * File tree of the package tarball (workspace viewer). Defaults to the active version.
     * @remarks `GET /agent-packages/:name/tree` — access: `authed`
     */
    getAgentPackageTree(params: {
        name: string;
        semver?: string;
        scope?: string;
        ownerProvider?: string;
        ownerSubject?: string;
    }): Promise<any>;

    /**
     * Artifact metadata.
     * @remarks `GET /sessions/:sessionId/artifacts/:filename/meta` — access: `session:read`
     */
    getArtifactMetadata(params: {
        sessionId: string;
        filename: string;
    }): Promise<any>;

    /**
     * The canvas data plane's last-value rows: current doc pointer + latest merged tick per slot. Snapshot source for live canvas subscriptions; empty when the deployment predates the plane.
     * @remarks `GET /management/sessions/:sessionId/canvas-live` — access: `session:read`
     */
    getCanvasLive(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Whether a public view link exists for this canvas (never the token itself), with created-at/by.
     * @remarks `GET /management/sessions/:sessionId/canvas-share-link` — access: `session:share`
     */
    getCanvasShareLink(params: {
        sessionId: string;
        slot?: number;
    }): Promise<any>;

    /**
     * One child outcome.
     * @remarks `GET /management/child-outcomes/:childSessionId` — access: `session:read`
     */
    getChildOutcome(params: {
        childSessionId: string;
    }): Promise<any>;

    /**
     * Read cluster feature policy.
     * @remarks `GET /management/features/cluster` — access: `authed`
     */
    getClusterFeatureFlags(params?: Record<string, never>): Promise<any>;

    /**
     * Profile of the authenticated principal.
     * @remarks `GET /me/profile` — access: `authed`
     */
    getCurrentUserProfile(params?: Record<string, never>): Promise<any>;

    /**
     * The deployment default model.
     * @remarks `GET /models/default` — access: `authed`
     */
    getDefaultModel(params?: Record<string, never>): Promise<any>;

    /**
     * Compatibility view of configured cluster, user and system model tuples.
     * @remarks `GET /defaults` — access: `authed`
     */
    getDefaults(params?: Record<string, never>): Promise<any>;

    /**
     * Durable embedder status. [enhanced]
     * @remarks `GET /facts/embedder` — access: `authed`
     */
    getEmbedderStatus(params?: Record<string, never>): Promise<any>;

    /**
     * Raw execution history events.
     * @remarks `GET /management/sessions/:sessionId/execution-history` — access: `session:read`
     */
    getExecutionHistory(params: {
        sessionId: string;
        executionId?: number;
    }): Promise<any>;

    /**
     * Soft-deleted facts awaiting reconciliation.
     * @remarks `GET /management/facts/tombstone-stats` — access: `fleet:read`
     */
    getFactsTombstoneStats(params: {
        ttlSeconds?: number;
    }): Promise<any>;

    /**
     * Fleet-wide graph node usage.
     * @remarks `GET /management/fleet/graph-node-usage` — access: `fleet:read`
     */
    getFleetGraphNodeUsage(params: {
        since?: string;
        includeDeleted?: boolean;
        limit?: number;
        nodeKeyLike?: string;
        kind?: string;
    }): Promise<any>;

    /**
     * Fleet-wide retrieval usage.
     * @remarks `GET /management/fleet/retrieval-usage` — access: `fleet:read`
     */
    getFleetRetrievalUsage(params: {
        since?: string;
        includeDeleted?: boolean;
    }): Promise<any>;

    /**
     * Fleet-wide skill usage.
     * @remarks `GET /management/fleet/skill-usage` — access: `fleet:read`
     */
    getFleetSkillUsage(params: {
        since?: string;
        includeDeleted?: boolean;
    }): Promise<any>;

    /**
     * Fleet-wide stats.
     * @remarks `GET /management/fleet/stats` — access: `fleet:read`
     */
    getFleetStats(params: {
        since?: string;
        includeDeleted?: boolean;
    }): Promise<any>;

    /**
     * One graph namespace descriptor.
     * @remarks `GET /graph/namespaces/:namespace` — access: `authed`
     */
    getGraphNamespace(params: {
        namespace: string;
    }): Promise<any>;

    /**
     * Latest turn response payload, if any.
     * @remarks `GET /management/sessions/:sessionId/latest-response` — access: `session:read`
     */
    getLatestResponse(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Aggregate legacy GHCP migration status; never returns credentials. [admin]
     * @remarks `GET /management/providers/legacy-key-migration` — access: `fleet:admin`
     */
    getLegacyProviderMigrationStatus(params?: Record<string, never>): Promise<any>;

    /**
     * Current retained values from the ephemeral live plane, optionally filtered by topic.
     * @remarks `GET /management/sessions/:sessionId/live` — access: `session:read`
     */
    getLive(params: {
        sessionId: string;
        topics?: any;
    }): Promise<any>;

    /**
     * Log tail availability.
     * @remarks `GET /system/log-config` — access: `authed`
     */
    getLogConfig(params?: Record<string, never>): Promise<any>;

    /**
     * Configured and effective user, cluster and system defaults plus per-system-agent overrides.
     * @remarks `GET /model-defaults` — access: `authed`
     */
    getModelDefaults(params?: Record<string, never>): Promise<any>;

    /**
     * Model templates grouped by provider type (catalogKind=provider_type); use listModels for viewer-usable runtime provider instances.
     * @remarks `GET /models/by-provider` — access: `authed`
     */
    getModelsByProvider(params?: Record<string, never>): Promise<any>;

    /**
     * Read my feature preferences and effective values.
     * @remarks `GET /management/users/me/features` — access: `authed`
     */
    getMyFeatureFlags(params?: Record<string, never>): Promise<any>;

    /**
     * Orchestration runtime stats.
     * @remarks `GET /management/sessions/:sessionId/orchestration-stats` — access: `session:read`
     */
    getOrchestrationStats(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Limits, usage against them, reset times, and the caller's own ceiling where an allowance applies. `names` is a comma-separated list; omit it for all of them.
     * @remarks `GET /providers/status` — access: `authed`
     */
    getProviderStatus(params: {
        names?: string;
    }): Promise<any>;

    /**
     * Where the tokens went: { totals, daily[], breakdown[] } over one filter set. dimension: session | user | provider | model | agent. Non-admins see only their own rows. `mine` narrows to the caller's own spend, resolved server-side — it carries no id, so it cannot name anybody else.
     * @remarks `GET /providers/usage` — access: `authed`
     */
    getProviderUsage(params: {
        days?: number;
        mine?: boolean;
        ownerUserId?: number;
        provider?: string;
        model?: string;
        sessionId?: string;
        chargeClass?: string;
        dimension?: string;
        limit?: number;
    }): Promise<any>;

    /**
     * The agent pivot from the usage ledger: tokens, turns, sessions and models per agent over the window (with '(none)' for sessions bound to no agent), each with a per-day series, plus a flat day-by-agent series for a stacked chart. Same viewer scoping and `providers` filter as the usage summary.
     * @remarks `GET /providers/usage-agents` — access: `authed`
     */
    getProviderUsageAgents(params: {
        days?: number;
        providers?: string;
    }): Promise<any>;

    /**
     * Every provider in the caller's namespace, each followed by its model-scoped limits, with used and quota figures for day, week and month — the caller's own and everyone's. A period with no limit reports its usage against an unlimited quota.
     * @remarks `GET /providers/usage-grid` — access: `authed`
     */
    getProviderUsageGrid(params?: Record<string, never>): Promise<any>;

    /**
     * The cluster summary from the usage ledger: today / week / month token totals with the input, output and cache split, a per-UTC-day series, and the per-model pivot across providers, reasoning efforts and context tiers. `providers` is a comma-separated list of names; absent means all. Admins see the whole cluster (system sessions included); everyone else sees their own turns.
     * @remarks `GET /providers/usage-summary` — access: `authed`
     */
    getProviderUsageSummary(params: {
        days?: number;
        providers?: string;
    }): Promise<any>;

    /**
     * Get one session view (live orchestration status).
     * @remarks `GET /sessions/:sessionId` — access: `session:read`
     */
    getSession(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * The caller's effective access to this session's tree: { visibility, relation, canWrite, canManage, owner }.
     * @remarks `GET /sessions/:sessionId/access` — access: `session:read`
     */
    getSessionAccess(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Session creation policy.
     * @remarks `GET /session-creation-policy` — access: `authed`
     */
    getSessionCreationPolicy(params?: Record<string, never>): Promise<any>;

    /**
     * Session events after a sequence number (reconnect catch-up). Optional eventTypes (JSON string array) narrows to those event types server-side.
     * @remarks `GET /management/sessions/:sessionId/events` — access: `session:read`
     */
    getSessionEvents(params: {
        sessionId: string;
        afterSeq?: number;
        limit?: number;
        eventTypes?: any;
    }): Promise<any>;

    /**
     * Older session events for history paging. Optional eventTypes (JSON string array) narrows to those event types server-side (chat transcript paging).
     * @remarks `GET /management/sessions/:sessionId/events-before` — access: `session:read`
     */
    getSessionEventsBefore(params: {
        sessionId: string;
        beforeSeq?: number;
        limit?: number;
        eventTypes?: any;
    }): Promise<any>;

    /**
     * Facts stats for one session.
     * @remarks `GET /management/sessions/:sessionId/facts-stats` — access: `session:read`
     */
    getSessionFactsStats(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Session footprint: context/compaction health, event-log and snapshot sizes, and an assessment (ok/elevated/degraded) with a recommendation. Control-plane only; TTL-cached.
     * @remarks `GET /management/sessions/:sessionId/footprint` — access: `session:read`
     */
    getSessionFootprint(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Graph edge-search usage for one session.
     * @remarks `GET /management/sessions/:sessionId/graph-edge-search-usage` — access: `session:read`
     */
    getSessionGraphEdgeSearchUsage(params: {
        sessionId: string;
        since?: string;
        limit?: number;
    }): Promise<any>;

    /**
     * Graph node usage for one session.
     * @remarks `GET /management/sessions/:sessionId/graph-node-usage` — access: `session:read`
     */
    getSessionGraphNodeUsage(params: {
        sessionId: string;
        since?: string;
        limit?: number;
        nodeKeyLike?: string;
        kind?: string;
    }): Promise<any>;

    /**
     * Recent graph search events for one session.
     * @remarks `GET /management/sessions/:sessionId/graph-searches` — access: `session:read`
     */
    getSessionGraphSearches(params: {
        sessionId: string;
        limit?: number;
    }): Promise<any>;

    /**
     * Per-session metric summary.
     * @remarks `GET /management/sessions/:sessionId/metric-summary` — access: `session:read`
     */
    getSessionMetricSummary(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Retrieval (facts/graph search) usage for one session.
     * @remarks `GET /management/sessions/:sessionId/retrieval-usage` — access: `session:read`
     */
    getSessionRetrievalUsage(params: {
        sessionId: string;
        since?: string;
    }): Promise<any>;

    /**
     * Read the pending signal wait, interruption flag, and buffered signal metadata (never inline payloads). Requires a signal-compatible execution.
     * @remarks `GET /sessions/:sessionId/signals` — access: `session:read`
     */
    getSessionSignalState(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Skill usage for one session.
     * @remarks `GET /management/sessions/:sessionId/skill-usage` — access: `session:read`
     */
    getSessionSkillUsage(params: {
        sessionId: string;
        since?: string;
    }): Promise<any>;

    /**
     * Live custom status + orchestration status.
     * @remarks `GET /management/sessions/:sessionId/status` — access: `session:read`
     */
    getSessionStatus(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Token totals grouped by model.
     * @remarks `GET /management/sessions/:sessionId/tokens-by-model` — access: `session:read`
     */
    getSessionTokensByModel(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Facts stats across the spawn tree.
     * @remarks `GET /management/sessions/:sessionId/tree-facts-stats` — access: `session:read`
     */
    getSessionTreeFactsStats(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Retrieval usage across the spawn tree.
     * @remarks `GET /management/sessions/:sessionId/tree-retrieval-usage` — access: `session:read`
     */
    getSessionTreeRetrievalUsage(params: {
        sessionId: string;
        since?: string;
    }): Promise<any>;

    /**
     * Skill usage across the spawn tree.
     * @remarks `GET /management/sessions/:sessionId/tree-skill-usage` — access: `session:read`
     */
    getSessionTreeSkillUsage(params: {
        sessionId: string;
        since?: string;
    }): Promise<any>;

    /**
     * Stats rolled up across the spawn tree.
     * @remarks `GET /management/sessions/:sessionId/tree-stats` — access: `session:read`
     */
    getSessionTreeStats(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Shared facts stats.
     * @remarks `GET /management/facts/shared-stats` — access: `fleet:read`
     */
    getSharedFactsStats(params?: Record<string, never>): Promise<any>;

    /**
     * Whether a System GitHub Copilot key is configured and who last changed it. [admin]
     * @remarks `GET /admin/system-github-copilot-key` — access: `fleet:admin` (admin)
     */
    getSystemGitHubCopilotKeyStatus(params?: Record<string, never>): Promise<any>;

    /**
     * Noisiest event emitters since a date.
     * @remarks `GET /management/events/top-emitters` — access: `fleet:read`
     */
    getTopEventEmitters(params: {
        since?: string;
        limit?: number;
    }): Promise<any>;

    /**
     * Read a user's feature preferences. [admin]
     * @remarks `GET /management/users/:userId/features` — access: `fleet:admin`
     */
    getUserFeatureFlags(params: {
        userId: string;
    }): Promise<any>;

    /**
     * Per-user stats.
     * @remarks `GET /management/users/stats` — access: `fleet:read`
     */
    getUserStats(params: {
        since?: string;
        includeDeleted?: boolean;
    }): Promise<any>;

    /**
     * Viewer-scoped webhook counts, routing backlog and dead-letter age with bounded dimensions.
     * @remarks `GET /webhooks/metrics` — access: `authed`
     */
    getWebhookMetrics(params?: Record<string, never>): Promise<any>;

    /**
     * Read an authorized receipt, disposition and receipt-to-session correlation.
     * @remarks `GET /webhooks/receipts/:receiptId` — access: `authed`
     */
    getWebhookReceipt(params: {
        receiptId: string;
    }): Promise<any>;

    /**
     * Live worker count.
     * @remarks `GET /system/workers` — access: `authed`
     */
    getWorkerCount(params?: Record<string, never>): Promise<any>;

    /**
     * Grant a user write access to a SHARED package ({ user: { provider, subject } }): publish, republish into it, pin, enable/disable — not scope, delete, or the editor list. Owner or admin. Revoked when the package is demoted to user scope.
     * @remarks `POST /agent-packages/:name/editors` — access: `authed`
     */
    grantAgentPackageEditor(params: {
        name: string;
        user?: any;
    }): Promise<any>;

    /**
     * Grant (or update) a targeted share ({ user: { provider, subject, email?, displayName? }, access: read|write }). Owner or admin.
     * @remarks `POST /sessions/:sessionId/shares` — access: `session:share`
     */
    grantSessionShare(params: {
        sessionId: string;
        user?: any;
        access?: any;
    }): Promise<any>;

    /**
     * Expand a subgraph around a node.
     * @remarks `POST /graph/neighbourhood` — access: `authed`
     */
    graphNeighbourhood(params: {
        nodeKey?: any;
        depth?: any;
        namespace?: any;
    }): Promise<any>;

    /**
     * Graph node/edge counts.
     * @remarks `GET /graph/stats` — access: `authed`
     */
    graphStats(params: {
        namespace?: string;
    }): Promise<any>;

    /**
     * Editors of the shared copy of a package. Visible to anyone who can see the package.
     * @remarks `GET /agent-packages/:name/editors` — access: `authed`
     */
    listAgentPackageEditors(params: {
        name: string;
    }): Promise<any>;

    /**
     * Agent packages visible to the caller: shared + own user-scope (admins see all).
     * @remarks `GET /agent-packages` — access: `authed`
     */
    listAgentPackages(params?: Record<string, never>): Promise<any>;

    /**
     * Per-worker installed package state (fleet adoption). Hard admin gate: the installed map enumerates every package name, including user-scope ones. [admin]
     * @remarks `GET /agent-packages/worker-state` — access: `fleet:admin` (admin)
     */
    listAgentWorkerState(params?: Record<string, never>): Promise<any>;

    /**
     * List artifacts for a session.
     * @remarks `GET /sessions/:sessionId/artifacts` — access: `session:read`
     */
    listArtifacts(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Authz audit records, newest first. Admin fleet-wide; owners for their own sessions (sessionId required).
     * @remarks `GET /management/authz-audit` — access: `authz:audit`
     */
    listAuthzAudit(params: {
        limit?: number;
        sessionId?: string;
    }): Promise<any>;

    /**
     * Child outcomes recorded under a parent session.
     * @remarks `GET /management/sessions/:parentSessionId/child-outcomes` — access: `session:read`
     */
    listChildOutcomes(params: {
        parentSessionId: string;
    }): Promise<any>;

    /**
     * Agents sessions can be created for.
     * @remarks `GET /agents` — access: `authed`
     */
    listCreatableAgents(params?: Record<string, never>): Promise<any>;

    /**
     * Read feature-setting audit history. [admin]
     * @remarks `GET /management/features/changes` — access: `fleet:admin`
     */
    listFeatureFlagChanges(params: {
        limit?: number;
    }): Promise<any>;

    /**
     * List code-defined feature flags and published defaults.
     * @remarks `GET /management/features/catalog` — access: `authed`
     */
    listFeatureFlags(params?: Record<string, never>): Promise<any>;

    /**
     * Find users to manage feature preferences. [admin]
     * @remarks `GET /management/features/users` — access: `fleet:admin`
     */
    listFeatureFlagUsers(params: {
        query?: string;
    }): Promise<any>;

    /**
     * List graph namespaces (corpora).
     * @remarks `GET /graph/namespaces` — access: `authed`
     */
    listGraphNamespaces(params: {
        prefix?: string;
        includeArchived?: boolean;
        includeDetails?: boolean;
    }): Promise<any>;

    /**
     * Member directory (provider/subject/email/displayName) for share autocomplete; excludes synthetic principals.
     * @remarks `GET /management/users` — access: `authed`
     */
    listKnownUsers(params: {
        limit?: number;
    }): Promise<any>;

    /**
     * Viewer-usable runtime provider instances (`catalogKind=runtime_provider`). Direct PilotSwarmManagementClient.listModels() is the provider-type template catalog (`catalogKind=provider_type`); use listRuntimeModels(viewer) for direct parity.
     * @remarks `GET /models` — access: `authed`
     */
    listModels(params?: Record<string, never>): Promise<any>;

    /**
     * Sessions waiting on a limit, allowance, hold, or a provider name that no longer resolves. Admins fleet-wide, everyone else their own.
     * @remarks `GET /providers/paused` — access: `authed`
     */
    listPausedSessions(params?: Record<string, never>): Promise<any>;

    /**
     * Providers the caller can use: every shared one plus their own. Admins also see other people's, marked usableByMe:false.
     * @remarks `GET /providers` — access: `authed`
     */
    listProviders(params?: Record<string, never>): Promise<any>;

    /**
     * List session groups.
     * @remarks `GET /management/session-groups` — access: `group:list`
     */
    listSessionGroups(params?: Record<string, never>): Promise<any>;

    /**
     * List session summaries.
     * @remarks `GET /sessions` — access: `session:list`
     */
    listSessions(params?: Record<string, never>): Promise<any>;

    /**
     * List targeted shares on this session's tree. Owner or admin.
     * @remarks `GET /sessions/:sessionId/shares` — access: `session:share`
     */
    listSessionShares(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Keyset-paginated session listing, optionally restricted to the authenticated viewer and to system or regular sessions.
     * @remarks `GET /management/sessions` — access: `session:list`
     */
    listSessionsPage(params: {
        limit?: number;
        cursor?: any;
        includeDeleted?: boolean;
        systemFilter?: string;
        viewerOnly?: boolean;
    }): Promise<any>;

    /**
     * List authorized signal endpoint metadata, never capability tokens.
     * @remarks `GET /sessions/:sessionId/signal-endpoints` — access: `session:write`
     */
    listSignalEndpoints(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * List viewer-authorized binding policy.
     * @remarks `GET /webhooks/bindings` — access: `authed`
     */
    listWebhookBindings(params?: Record<string, never>): Promise<any>;

    /**
     * List viewer-authorized connectors with redacted authentication metadata.
     * @remarks `GET /webhooks/connectors` — access: `authed`
     */
    listWebhookConnectors(params?: Record<string, never>): Promise<any>;

    /**
     * Page viewer-authorized redacted delivery timelines; inline payloads are never returned.
     * @remarks `GET /webhooks/receipts` — access: `authed`
     */
    listWebhookReceipts(params: {
        query?: any;
    }): Promise<any>;

    /**
     * List viewer-authorized approved templates.
     * @remarks `GET /webhooks/templates` — access: `authed`
     */
    listWebhookSessionTemplates(params?: Record<string, never>): Promise<any>;

    /**
     * Worker registry (0040): every registered worker with pool, lifecycle phase, liveness, write-once info, health snapshot, and per-domain state. Hard admin gate. [admin]
     * @remarks `GET /workers` — access: `fleet:admin` (admin)
     */
    listWorkers(params?: Record<string, never>): Promise<any>;

    /**
     * Deprecated alias of placeSessionsInGroup.
     * @remarks `POST /management/session-groups/move` — access: `authed`
     */
    moveSessionsToGroup(params: {
        groupId?: any;
        sessionIds?: any;
    }): Promise<any>;

    /**
     * Pin the active version (rollback). Creator or admin; fleet converges on the next epoch poll. `scope` picks which same-named copy.
     * @remarks `PUT /agent-packages/:name/active` — access: `authed`
     */
    pinAgentPackageVersion(params: {
        name: string;
        semver?: any;
        scope?: any;
        ownerProvider?: any;
        ownerSubject?: any;
    }): Promise<any>;

    /**
     * Place session trees into one of the caller's groups (groupId null = ungroup). Requires read access to each session; changes no shared session data.
     * @remarks `POST /management/session-groups/place` — access: `authed`
     */
    placeSessionsInGroup(params: {
        groupId?: any;
        sessionIds?: any;
    }): Promise<any>;

    /**
     * Prune summaries of deleted sessions.
     * @remarks `POST /management/summaries/prune-deleted` — access: `fleet:admin`
     */
    pruneDeletedSummaries(params: {
        olderThan?: any;
    }): Promise<any>;

    /**
     * Queue a typed durable signal. Starts an unstarted session without a prompt; wake defaults to false. Returns a queued receipt, not a consumption acknowledgement.
     * @remarks `POST /sessions/:sessionId/signals/:name` — access: `session:write`
     */
    raiseSignal(params: {
        sessionId: string;
        name: string;
        data?: any;
        payloadRef?: any;
        signalId?: any;
        wake?: any;
    }): Promise<any>;

    /**
     * Artifact content as base64 (JSON envelope; maxBytes caps the read, truncated flag set when hit).
     * @remarks `GET /sessions/:sessionId/artifacts/:filename/base64` — access: `session:read`
     */
    readArtifactBase64(params: {
        sessionId: string;
        filename: string;
        maxBytes?: number;
    }): Promise<any>;

    /**
     * Read the canvas KV store: entries under a prefix (cursor-paged, ≤200) or one key, plus `me` (relation, canWrite) and the canvas policy. The page's canvas-kv-ready payload.
     * @remarks `GET /management/sessions/:sessionId/canvas-kv` — access: `canvas:read`
     */
    readCanvasKv(params: {
        sessionId: string;
        slot?: number;
        prefix?: string;
        limit?: number;
        after?: string;
        key?: string;
    }): Promise<any>;

    /**
     * Read facts (ReadFactsQuery params).
     * @remarks `GET /facts` — access: `facts:read`
     */
    readFacts(params: {
        keyPattern?: string;
        scopeKeys?: any;
        tags?: any;
        sessionId?: string;
        agentId?: string;
        limit?: number;
        scope?: string;
    }): Promise<any>;

    /**
     * Regenerate the session's transcript in place (epoch rebirth): archive, distill, and recreate the Copilot session at a turn boundary. Enqueue-then-observe; outcomes arrive as session.regenerate_* events.
     * @remarks `POST /management/sessions/:sessionId/regenerate` — access: `session:manage`
     */
    regenerateSession(params: {
        sessionId: string;
        options?: any;
    }): Promise<any>;

    /**
     * Delete the public view link; the canvas returns to unlinked.
     * @remarks `POST /management/sessions/:sessionId/canvas-share-link/remove` — access: `session:share`
     */
    removeCanvasShareLink(params: {
        sessionId: string;
        slot?: any;
    }): Promise<any>;

    /**
     * Drop one limit. Returns whether there was one.
     * @remarks `DELETE /providers/:name/limit` — access: `authed`
     */
    removeProviderLimit(params: {
        name: string;
        period?: string;
        model?: string;
    }): Promise<any>;

    /**
     * Rename a session.
     * @remarks `PATCH /management/sessions/:sessionId` — access: `session:manage`
     */
    renameSession(params: {
        sessionId: string;
        title?: any;
    }): Promise<any>;

    /**
     * Explicitly confirmed replay of a failed receipt under current authorization; confirmed must be true.
     * @remarks `POST /webhooks/receipts/:receiptId/replay` — access: `authed`
     */
    replayWebhookReceipt(params: {
        receiptId: string;
        confirmed?: any;
    }): Promise<any>;

    /**
     * Publish an existing version's exact bytes into the same-named package in another scope (user↔shared). THE update path for an already-published shared package — promote can only move a row to an unused name. Creator or admin.
     * @remarks `POST /agent-packages/:name/republish` — access: `authed`
     */
    republishAgentPackageVersion(params: {
        name: string;
        semver?: any;
        targetScope?: any;
        ownerProvider?: any;
        ownerSubject?: any;
    }): Promise<any>;

    /**
     * Mint-or-rotate the ONE public view token for this canvas. Returns the raw token exactly once; the previous link stops working immediately.
     * @remarks `POST /management/sessions/:sessionId/canvas-share-link/reset` — access: `session:share`
     */
    resetCanvasShareLink(params: {
        sessionId: string;
        slot?: any;
    }): Promise<any>;

    /**
     * Reset cluster feature policy to published defaults. [admin]
     * @remarks `DELETE /management/features/cluster/:featureKey` — access: `fleet:admin`
     */
    resetClusterFeatureFlag(params: {
        featureKey: string;
        expectedRevision?: string;
        requestId?: string;
    }): Promise<any>;

    /**
     * Restart a system session (complete | terminate | hard_delete).
     * @remarks `POST /management/sessions/:agentIdOrSessionId/restart-system` — access: `fleet:admin`
     */
    restartSystemSession(params: {
        agentIdOrSessionId: string;
        options?: any;
    }): Promise<any>;

    /**
     * Revoke a user's editor grant on a shared package ({ user: { provider, subject } }). Owner or admin; idempotent.
     * @remarks `POST /agent-packages/:name/editors/revoke` — access: `authed`
     */
    revokeAgentPackageEditor(params: {
        name: string;
        user?: any;
    }): Promise<any>;

    /**
     * Revoke a targeted share ({ user: { provider, subject } }). Owner or admin.
     * @remarks `POST /sessions/:sessionId/shares/revoke` — access: `session:share`
     */
    revokeSessionShare(params: {
        sessionId: string;
        user?: any;
    }): Promise<any>;

    /**
     * Revoke an owned signal endpoint; the target session is untouched.
     * @remarks `DELETE /signal-endpoints/:endpointId` — access: `authed`
     */
    revokeSignalEndpoint(params: {
        endpointId: string;
    }): Promise<any>;

    /**
     * Revoke a binding without changing its target session.
     * @remarks `DELETE /webhooks/bindings/:bindingId` — access: `authed`
     */
    revokeWebhookBinding(params: {
        bindingId: string;
    }): Promise<any>;

    /**
     * Revoke a connector and prevent subsequent routing attempts.
     * @remarks `DELETE /webhooks/connectors/:connectorId` — access: `authed`
     */
    revokeWebhookConnector(params: {
        connectorId: string;
    }): Promise<any>;

    /**
     * Revoke approval for future session creation through a template.
     * @remarks `DELETE /webhooks/templates/:templateId` — access: `authed`
     */
    revokeWebhookSessionTemplate(params: {
        templateId: string;
    }): Promise<any>;

    /**
     * Retrieval over facts (lexical | semantic | hybrid). [enhanced]
     * @remarks `POST /facts/search` — access: `facts:read`
     */
    searchFacts(params: {
        query?: any;
        opts?: any;
    }): Promise<any>;

    /**
     * Search graph edges (GraphEdgeQuery).
     * @remarks `POST /graph/edges/search` — access: `authed`
     */
    searchGraphEdges(params: {
        query?: any;
    }): Promise<any>;

    /**
     * Search graph nodes (GraphNodeQuery).
     * @remarks `POST /graph/nodes/search` — access: `authed`
     */
    searchGraphNodes(params: {
        query?: any;
    }): Promise<any>;

    /**
     * Answer a pending input-required question; options.expectedQuestion binds to the observed question and iteration.
     * @remarks `POST /sessions/:sessionId/answers` — access: `session:write`
     */
    sendAnswer(params: {
        sessionId: string;
        answer?: any;
        options?: any;
    }): Promise<any>;

    /**
     * Send a prompt (options: { enqueueOnly?, clientMessageIds?, attachments?: [{filename}] } — attachments reference image artifacts already uploaded to the session).
     * @remarks `POST /sessions/:sessionId/messages` — access: `session:write`
     */
    sendMessage(params: {
        sessionId: string;
        prompt?: any;
        options?: any;
    }): Promise<any>;

    /**
     * Deprecated compatibility wrapper for raiseSignal(eventName, { data }); never a raw prompt or command.
     * @remarks `POST /sessions/:sessionId/events` — access: `session:write`
     */
    sendSessionEvent(params: {
        sessionId: string;
        eventName?: any;
        data?: any;
    }): Promise<any>;

    /**
     * Enable/disable a package fleet-wide. Creator or admin. `scope` picks which same-named copy.
     * @remarks `PUT /agent-packages/:name/enabled` — access: `authed`
     */
    setAgentPackageEnabled(params: {
        name: string;
        enabled?: any;
        scope?: any;
        ownerProvider?: any;
        ownerSubject?: any;
    }): Promise<any>;

    /**
     * Promote (shared) or demote (user). The source copy is implied by the direction: promote moves the caller's (or named owner's) user copy, demote moves the shared one. Creator or admin; running agents unaffected.
     * @remarks `PUT /agent-packages/:name/scope` — access: `authed`
     */
    setAgentPackageScope(params: {
        name: string;
        scope?: any;
        ownerProvider?: any;
        ownerSubject?: any;
    }): Promise<any>;

    /**
     * Pin/unpin an artifact (pinned artifacts survive retention sweeps).
     * @remarks `PUT /sessions/:sessionId/artifacts/:filename/pinned` — access: `session:manage`
     */
    setArtifactPinned(params: {
        sessionId: string;
        filename: string;
        pinned?: any;
    }): Promise<any>;

    /**
     * Set who may write this canvas's KV: owner (default) | readers (anyone the session is read-shared with) | link. Owner or admin.
     * @remarks `PUT /management/sessions/:sessionId/canvas-kv/access` — access: `session:share`
     */
    setCanvasKvAccess(params: {
        sessionId: string;
        slot?: any;
        access?: any;
    }): Promise<any>;

    /**
     * Deprecated alias for setModelDefault(scope=cluster). [admin]
     * @remarks `PUT /management/defaults` — access: `fleet:admin`
     */
    setClusterDefault(params: {
        provider?: any;
        model?: any;
        reasoning?: any;
        context?: any;
    }): Promise<any>;

    /**
     * Set cluster feature policy atomically. [admin]
     * @remarks `PUT /management/features/cluster/:featureKey` — access: `fleet:admin`
     */
    setClusterFeatureFlag(params: {
        featureKey: string;
        enabled?: any;
        allowUserOverride?: any;
        expectedRevision?: any;
        requestId?: any;
    }): Promise<any>;

    /**
     * Set (or clear with null) the per-user GitHub Copilot key.
     * @remarks `PUT /me/github-copilot-key` — access: `authed`
     */
    setCurrentUserGitHubCopilotKey(params: {
        key?: any;
    }): Promise<any>;

    /**
     * Replace profile settings.
     * @remarks `PATCH /me/profile/settings` — access: `authed`
     */
    setCurrentUserProfileSettings(params: {
        settings?: any;
    }): Promise<any>;

    /**
     * Set or clear the user or cluster ordinary-session default. Cluster scope requires admin.
     * @remarks `PUT /model-defaults` — access: `authed`
     */
    setModelDefault(params: {
        scope?: any;
        provider?: any;
        model?: any;
        reasoningEffort?: any;
        contextTier?: any;
    }): Promise<any>;

    /**
     * The caller's prefill for new sessions. A null provider clears it.
     * @remarks `PUT /me/default` — access: `authed`
     */
    setMyDefault(params: {
        provider?: any;
        model?: any;
        reasoning?: any;
        context?: any;
    }): Promise<any>;

    /**
     * Set my preference; locked cluster policy still takes precedence.
     * @remarks `PUT /management/users/me/features/:featureKey` — access: `authed`
     */
    setMyFeatureFlag(params: {
        featureKey: string;
        enabled?: any;
        expectedRevision?: any;
        requestId?: any;
    }): Promise<any>;

    /**
     * The share of each limit one person may use, 1..100. 100 means no per-person ceiling. Shared providers only. [admin]
     * @remarks `PUT /management/providers/:name/allowance` — access: `fleet:admin`
     */
    setProviderAllowance(params: {
        name: string;
        pct?: any;
    }): Promise<any>;

    /**
     * Pause new turns against a provider. Neither untilUtc nor release = a hold with no end. [admin]
     * @remarks `PUT /management/providers/:name/hold` — access: `fleet:admin`
     */
    setProviderHold(params: {
        name: string;
        untilUtc?: any;
        release?: any;
    }): Promise<any>;

    /**
     * Save one limit (day | week | month, all models or one). The same combination replaces what was there. Admin on a shared provider, owner on a personal one.
     * @remarks `PUT /providers/:name/limit` — access: `authed`
     */
    setProviderLimit(params: {
        name: string;
        period?: any;
        model?: any;
        tokens?: any;
    }): Promise<any>;

    /**
     * Allow or refuse system-session use of the calling admin's personal provider. [admin]
     * @remarks `PUT /management/providers/:name/system-use` — access: `fleet:admin`
     */
    setProviderSystemUse(params: {
        name: string;
        enabled?: any;
    }): Promise<any>;

    /**
     * Switch the session model ({ model, reasoningEffort?, contextTier? }).
     * @remarks `POST /management/sessions/:sessionId/model` — access: `session:manage`
     */
    setSessionModel(params: {
        sessionId: string;
        options?: any;
    }): Promise<any>;

    /**
     * Set the tree's sharing level (private | shared_read | shared_write). Owner or admin.
     * @remarks `PUT /sessions/:sessionId/visibility` — access: `session:share`
     */
    setSessionVisibility(params: {
        sessionId: string;
        visibility?: any;
    }): Promise<any>;

    /**
     * Set (or clear with null) the System user's GitHub Copilot key, used by ownerless system sessions. [admin]
     * @remarks `PUT /admin/system-github-copilot-key` — access: `fleet:admin` (admin)
     */
    setSystemGitHubCopilotKey(params: {
        key?: any;
    }): Promise<any>;

    /**
     * Set or clear the system-session default and optionally restart inheriting sessions. [admin]
     * @remarks `PUT /management/system-model-default` — access: `fleet:admin`
     */
    setSystemModelDefault(params: {
        provider?: any;
        model?: any;
        reasoningEffort?: any;
        contextTier?: any;
        restartExisting?: any;
    }): Promise<any>;

    /**
     * Set one persistent system-agent model override. [admin]
     * @remarks `PUT /management/system-sessions/:agentId/model` — access: `fleet:admin`
     */
    setSystemSessionModel(params: {
        agentId: string;
        provider?: any;
        model?: any;
        reasoningEffort?: any;
        contextTier?: any;
    }): Promise<any>;

    /**
     * Set a user's feature preference. [admin]
     * @remarks `PUT /management/users/:userId/features/:featureKey` — access: `fleet:admin`
     */
    setUserFeatureFlag(params: {
        userId: string;
        featureKey: string;
        enabled?: any;
        expectedRevision?: any;
        requestId?: any;
    }): Promise<any>;

    /**
     * Semantic nearest-neighbours of a known fact. [enhanced]
     * @remarks `POST /facts/similar` — access: `facts:read`
     */
    similarFacts(params: {
        scopeKey?: any;
        opts?: any;
    }): Promise<any>;

    /**
     * Start the durable embedder loop. [enhanced, admin]
     * @remarks `POST /facts/embedder/start` — access: `fleet:admin` (admin)
     */
    startFactsEmbedder(params: {
        intervalSeconds?: any;
        batch?: any;
    }): Promise<any>;

    /**
     * Stop the durable embedder loop. [enhanced, admin]
     * @remarks `POST /facts/embedder/stop` — access: `fleet:admin` (admin)
     */
    stopFactsEmbedder(params: {
        reason?: any;
    }): Promise<any>;

    /**
     * Abort the in-flight turn or cancel the observed parked signal wait without cancelling the session.
     * @remarks `POST /management/sessions/:sessionId/stop-turn` — access: `session:write`
     */
    stopSessionTurn(params: {
        sessionId: string;
        options?: any;
    }): Promise<any>;

    /**
     * Store a fact or facts (StoreFactInput | StoreFactInput[]).
     * @remarks `POST /facts` — access: `facts:write`
     */
    storeFact(params: {
        input?: any;
    }): Promise<any>;

    /**
     * Dry-run normalized event matching and persisted policy; creates no sessions and does not bypass current host admission.
     * @remarks `POST /webhooks/bindings/:bindingId/test` — access: `authed`
     */
    testWebhookBinding(params: {
        bindingId: string;
        event?: any;
    }): Promise<any>;

    /**
     * Remove my preference and inherit cluster policy.
     * @remarks `DELETE /management/users/me/features/:featureKey` — access: `authed`
     */
    unsetMyFeatureFlag(params: {
        featureKey: string;
        expectedRevision?: string;
        requestId?: string;
    }): Promise<any>;

    /**
     * Remove a user's preference and restore inheritance. [admin]
     * @remarks `DELETE /management/users/:userId/features/:featureKey` — access: `fleet:admin`
     */
    unsetUserFeatureFlag(params: {
        userId: string;
        featureKey: string;
        expectedRevision?: string;
        requestId?: string;
    }): Promise<any>;

    /**
     * Replace the credential on one of your own personal providers without changing its name, defaults, or usage history.
     * @remarks `PUT /me/providers/:name/credential` — access: `authed`
     */
    updateMyProviderCredential(params: {
        name: string;
        credentials?: any;
    }): Promise<any>;

    /**
     * Update group title/description.
     * @remarks `PATCH /management/session-groups/:groupId` — access: `group:manage`
     */
    updateSessionGroup(params: {
        groupId: string;
        patch?: any;
    }): Promise<any>;

    /**
     * Replace the credential on a shared provider without changing its name, defaults, routing, or usage history. [admin]
     * @remarks `PUT /management/providers/:name/credential` — access: `fleet:admin`
     */
    updateSharedProviderCredential(params: {
        name: string;
        credentials?: any;
    }): Promise<any>;

    /**
     * Update an owned binding with expectedRevision and current target authorization.
     * @remarks `PATCH /webhooks/bindings/:bindingId` — access: `authed`
     */
    updateWebhookBinding(params: {
        bindingId: string;
        patch?: any;
    }): Promise<any>;

    /**
     * Update a connector with expectedRevision; credential-reference changes require admin approval.
     * @remarks `PATCH /webhooks/connectors/:connectorId` — access: `authed`
     */
    updateWebhookConnector(params: {
        connectorId: string;
        patch?: any;
    }): Promise<any>;

    /**
     * Update bounded receipt/replay retention with expectedRevision. Active work and delivery/creation deduplication are never aged out.
     * @remarks `PATCH /webhooks/retention` — access: `fleet:admin`
     */
    updateWebhookRetentionPolicy(params: {
        patch?: any;
    }): Promise<any>;

    /**
     * Update a template with expectedRevision; configuration and prompt changes require admin approval.
     * @remarks `PATCH /webhooks/templates/:templateId` — access: `authed`
     */
    updateWebhookSessionTemplate(params: {
        templateId: string;
        patch?: any;
    }): Promise<any>;

    /**
     * Publish a package from inline files ([{path, contentBase64}], ≤ 2 MB total); validates, canonically packs, and registers as the caller.
     * @remarks `POST /agent-packages/upload` — access: `authed`
     */
    uploadAgentPackage(params: {
        files?: any;
        scope?: any;
    }): Promise<any>;

    /**
     * Upload artifact content (base64 for binary; 2 MB JSON limit).
     * @remarks `PUT /sessions/:sessionId/artifacts/:filename` — access: `session:write`
     */
    uploadArtifact(params: {
        sessionId: string;
        filename: string;
        content?: any;
        contentType?: any;
        contentEncoding?: any;
    }): Promise<any>;

    /**
     * Upsert a graph edge (GraphEdgeInput).
     * @remarks `POST /graph/edges` — access: `authed`
     */
    upsertGraphEdge(params: {
        input?: any;
    }): Promise<any>;

    /**
     * Register/update a graph namespace. [admin]
     * @remarks `POST /graph/namespaces` — access: `fleet:admin` (admin)
     */
    upsertGraphNamespace(params: {
        input?: any;
    }): Promise<any>;

    /**
     * Upsert a graph node (GraphNodeInput).
     * @remarks `POST /graph/nodes` — access: `authed`
     */
    upsertGraphNode(params: {
        input?: any;
    }): Promise<any>;

    /**
     * Long-poll for a status version change (server-capped timeout).
     * @remarks `GET /management/sessions/:sessionId/status/wait` — access: `session:read`
     */
    waitForStatusChange(params: {
        sessionId: string;
        afterVersion?: number;
        timeoutMs?: number;
    }): Promise<any>;

    /**
     * Write the canvas KV store: ops [{op: put|delete, key, value?, ifMatch?}] (≤50). Each op is answered individually; who may write is the canvas policy × the app's kv.write switch; req/* rows from collaborators are capped to status suggested.
     * @remarks `POST /management/sessions/:sessionId/canvas-kv` — access: `canvas:write`
     */
    writeCanvasKv(params: {
        sessionId: string;
        slot?: any;
        ops?: any;
    }): Promise<any>;
}

/**
 * Build the operation surface bound to a transport callback.
 *
 * @param callOp invoked as `(opName, params)`; must resolve the JSON result
 */
export function createManagementOps(
    callOp: (name: string, params: Record<string, unknown>) => Promise<any>,
): ManagementOps {
    return {
        adoptLegacySystemGitHubCopilotKey: (params: Record<string, unknown> = {}) => callOp("adoptLegacySystemGitHubCopilotKey", params),
        assignSessionsToGroup: (params: Record<string, unknown> = {}) => callOp("assignSessionsToGroup", params),
        cancelPendingMessage: (params: Record<string, unknown> = {}) => callOp("cancelPendingMessage", params),
        cancelSession: (params: Record<string, unknown> = {}) => callOp("cancelSession", params),
        cancelSessionGroup: (params: Record<string, unknown> = {}) => callOp("cancelSessionGroup", params),
        clearProviderRoutingDependencies: (params: Record<string, unknown> = {}) => callOp("clearProviderRoutingDependencies", params),
        clearSystemSessionModel: (params: Record<string, unknown> = {}) => callOp("clearSystemSessionModel", params),
        completeSession: (params: Record<string, unknown> = {}) => callOp("completeSession", params),
        completeSessionGroup: (params: Record<string, unknown> = {}) => callOp("completeSessionGroup", params),
        copyArtifact: (params: Record<string, unknown> = {}) => callOp("copyArtifact", params),
        createMyProvider: (params: Record<string, unknown> = {}) => callOp("createMyProvider", params),
        createProvider: (params: Record<string, unknown> = {}) => callOp("createProvider", params),
        createSession: (params: Record<string, unknown> = {}) => callOp("createSession", params),
        createSessionForAgent: (params: Record<string, unknown> = {}) => callOp("createSessionForAgent", params),
        createSessionGroup: (params: Record<string, unknown> = {}) => callOp("createSessionGroup", params),
        createSignalEndpoint: (params: Record<string, unknown> = {}) => callOp("createSignalEndpoint", params),
        createWebhookBinding: (params: Record<string, unknown> = {}) => callOp("createWebhookBinding", params),
        createWebhookConnector: (params: Record<string, unknown> = {}) => callOp("createWebhookConnector", params),
        createWebhookSessionTemplate: (params: Record<string, unknown> = {}) => callOp("createWebhookSessionTemplate", params),
        deleteAgentPackage: (params: Record<string, unknown> = {}) => callOp("deleteAgentPackage", params),
        deleteArtifact: (params: Record<string, unknown> = {}) => callOp("deleteArtifact", params),
        deleteFact: (params: Record<string, unknown> = {}) => callOp("deleteFact", params),
        deleteGraphEdge: (params: Record<string, unknown> = {}) => callOp("deleteGraphEdge", params),
        deleteGraphNamespace: (params: Record<string, unknown> = {}) => callOp("deleteGraphNamespace", params),
        deleteGraphNode: (params: Record<string, unknown> = {}) => callOp("deleteGraphNode", params),
        deleteMyProvider: (params: Record<string, unknown> = {}) => callOp("deleteMyProvider", params),
        deleteProvider: (params: Record<string, unknown> = {}) => callOp("deleteProvider", params),
        deleteSession: (params: Record<string, unknown> = {}) => callOp("deleteSession", params),
        deleteSessionGroup: (params: Record<string, unknown> = {}) => callOp("deleteSessionGroup", params),
        downloadArtifact: (params: Record<string, unknown> = {}) => callOp("downloadArtifact", params),
        exportExecutionHistory: (params: Record<string, unknown> = {}) => callOp("exportExecutionHistory", params),
        factsCapabilities: (params: Record<string, unknown> = {}) => callOp("factsCapabilities", params),
        forcePurgeFacts: (params: Record<string, unknown> = {}) => callOp("forcePurgeFacts", params),
        getAgentPackage: (params: Record<string, unknown> = {}) => callOp("getAgentPackage", params),
        getAgentPackageFile: (params: Record<string, unknown> = {}) => callOp("getAgentPackageFile", params),
        getAgentPackageTree: (params: Record<string, unknown> = {}) => callOp("getAgentPackageTree", params),
        getArtifactMetadata: (params: Record<string, unknown> = {}) => callOp("getArtifactMetadata", params),
        getCanvasLive: (params: Record<string, unknown> = {}) => callOp("getCanvasLive", params),
        getCanvasShareLink: (params: Record<string, unknown> = {}) => callOp("getCanvasShareLink", params),
        getChildOutcome: (params: Record<string, unknown> = {}) => callOp("getChildOutcome", params),
        getClusterFeatureFlags: (params: Record<string, unknown> = {}) => callOp("getClusterFeatureFlags", params),
        getCurrentUserProfile: (params: Record<string, unknown> = {}) => callOp("getCurrentUserProfile", params),
        getDefaultModel: (params: Record<string, unknown> = {}) => callOp("getDefaultModel", params),
        getDefaults: (params: Record<string, unknown> = {}) => callOp("getDefaults", params),
        getEmbedderStatus: (params: Record<string, unknown> = {}) => callOp("getEmbedderStatus", params),
        getExecutionHistory: (params: Record<string, unknown> = {}) => callOp("getExecutionHistory", params),
        getFactsTombstoneStats: (params: Record<string, unknown> = {}) => callOp("getFactsTombstoneStats", params),
        getFleetGraphNodeUsage: (params: Record<string, unknown> = {}) => callOp("getFleetGraphNodeUsage", params),
        getFleetRetrievalUsage: (params: Record<string, unknown> = {}) => callOp("getFleetRetrievalUsage", params),
        getFleetSkillUsage: (params: Record<string, unknown> = {}) => callOp("getFleetSkillUsage", params),
        getFleetStats: (params: Record<string, unknown> = {}) => callOp("getFleetStats", params),
        getGraphNamespace: (params: Record<string, unknown> = {}) => callOp("getGraphNamespace", params),
        getLatestResponse: (params: Record<string, unknown> = {}) => callOp("getLatestResponse", params),
        getLegacyProviderMigrationStatus: (params: Record<string, unknown> = {}) => callOp("getLegacyProviderMigrationStatus", params),
        getLive: (params: Record<string, unknown> = {}) => callOp("getLive", params),
        getLogConfig: (params: Record<string, unknown> = {}) => callOp("getLogConfig", params),
        getModelDefaults: (params: Record<string, unknown> = {}) => callOp("getModelDefaults", params),
        getModelsByProvider: (params: Record<string, unknown> = {}) => callOp("getModelsByProvider", params),
        getMyFeatureFlags: (params: Record<string, unknown> = {}) => callOp("getMyFeatureFlags", params),
        getOrchestrationStats: (params: Record<string, unknown> = {}) => callOp("getOrchestrationStats", params),
        getProviderStatus: (params: Record<string, unknown> = {}) => callOp("getProviderStatus", params),
        getProviderUsage: (params: Record<string, unknown> = {}) => callOp("getProviderUsage", params),
        getProviderUsageAgents: (params: Record<string, unknown> = {}) => callOp("getProviderUsageAgents", params),
        getProviderUsageGrid: (params: Record<string, unknown> = {}) => callOp("getProviderUsageGrid", params),
        getProviderUsageSummary: (params: Record<string, unknown> = {}) => callOp("getProviderUsageSummary", params),
        getSession: (params: Record<string, unknown> = {}) => callOp("getSession", params),
        getSessionAccess: (params: Record<string, unknown> = {}) => callOp("getSessionAccess", params),
        getSessionCreationPolicy: (params: Record<string, unknown> = {}) => callOp("getSessionCreationPolicy", params),
        getSessionEvents: (params: Record<string, unknown> = {}) => callOp("getSessionEvents", params),
        getSessionEventsBefore: (params: Record<string, unknown> = {}) => callOp("getSessionEventsBefore", params),
        getSessionFactsStats: (params: Record<string, unknown> = {}) => callOp("getSessionFactsStats", params),
        getSessionFootprint: (params: Record<string, unknown> = {}) => callOp("getSessionFootprint", params),
        getSessionGraphEdgeSearchUsage: (params: Record<string, unknown> = {}) => callOp("getSessionGraphEdgeSearchUsage", params),
        getSessionGraphNodeUsage: (params: Record<string, unknown> = {}) => callOp("getSessionGraphNodeUsage", params),
        getSessionGraphSearches: (params: Record<string, unknown> = {}) => callOp("getSessionGraphSearches", params),
        getSessionMetricSummary: (params: Record<string, unknown> = {}) => callOp("getSessionMetricSummary", params),
        getSessionRetrievalUsage: (params: Record<string, unknown> = {}) => callOp("getSessionRetrievalUsage", params),
        getSessionSignalState: (params: Record<string, unknown> = {}) => callOp("getSessionSignalState", params),
        getSessionSkillUsage: (params: Record<string, unknown> = {}) => callOp("getSessionSkillUsage", params),
        getSessionStatus: (params: Record<string, unknown> = {}) => callOp("getSessionStatus", params),
        getSessionTokensByModel: (params: Record<string, unknown> = {}) => callOp("getSessionTokensByModel", params),
        getSessionTreeFactsStats: (params: Record<string, unknown> = {}) => callOp("getSessionTreeFactsStats", params),
        getSessionTreeRetrievalUsage: (params: Record<string, unknown> = {}) => callOp("getSessionTreeRetrievalUsage", params),
        getSessionTreeSkillUsage: (params: Record<string, unknown> = {}) => callOp("getSessionTreeSkillUsage", params),
        getSessionTreeStats: (params: Record<string, unknown> = {}) => callOp("getSessionTreeStats", params),
        getSharedFactsStats: (params: Record<string, unknown> = {}) => callOp("getSharedFactsStats", params),
        getSystemGitHubCopilotKeyStatus: (params: Record<string, unknown> = {}) => callOp("getSystemGitHubCopilotKeyStatus", params),
        getTopEventEmitters: (params: Record<string, unknown> = {}) => callOp("getTopEventEmitters", params),
        getUserFeatureFlags: (params: Record<string, unknown> = {}) => callOp("getUserFeatureFlags", params),
        getUserStats: (params: Record<string, unknown> = {}) => callOp("getUserStats", params),
        getWebhookMetrics: (params: Record<string, unknown> = {}) => callOp("getWebhookMetrics", params),
        getWebhookReceipt: (params: Record<string, unknown> = {}) => callOp("getWebhookReceipt", params),
        getWorkerCount: (params: Record<string, unknown> = {}) => callOp("getWorkerCount", params),
        grantAgentPackageEditor: (params: Record<string, unknown> = {}) => callOp("grantAgentPackageEditor", params),
        grantSessionShare: (params: Record<string, unknown> = {}) => callOp("grantSessionShare", params),
        graphNeighbourhood: (params: Record<string, unknown> = {}) => callOp("graphNeighbourhood", params),
        graphStats: (params: Record<string, unknown> = {}) => callOp("graphStats", params),
        listAgentPackageEditors: (params: Record<string, unknown> = {}) => callOp("listAgentPackageEditors", params),
        listAgentPackages: (params: Record<string, unknown> = {}) => callOp("listAgentPackages", params),
        listAgentWorkerState: (params: Record<string, unknown> = {}) => callOp("listAgentWorkerState", params),
        listArtifacts: (params: Record<string, unknown> = {}) => callOp("listArtifacts", params),
        listAuthzAudit: (params: Record<string, unknown> = {}) => callOp("listAuthzAudit", params),
        listChildOutcomes: (params: Record<string, unknown> = {}) => callOp("listChildOutcomes", params),
        listCreatableAgents: (params: Record<string, unknown> = {}) => callOp("listCreatableAgents", params),
        listFeatureFlagChanges: (params: Record<string, unknown> = {}) => callOp("listFeatureFlagChanges", params),
        listFeatureFlags: (params: Record<string, unknown> = {}) => callOp("listFeatureFlags", params),
        listFeatureFlagUsers: (params: Record<string, unknown> = {}) => callOp("listFeatureFlagUsers", params),
        listGraphNamespaces: (params: Record<string, unknown> = {}) => callOp("listGraphNamespaces", params),
        listKnownUsers: (params: Record<string, unknown> = {}) => callOp("listKnownUsers", params),
        listModels: (params: Record<string, unknown> = {}) => callOp("listModels", params),
        listPausedSessions: (params: Record<string, unknown> = {}) => callOp("listPausedSessions", params),
        listProviders: (params: Record<string, unknown> = {}) => callOp("listProviders", params),
        listSessionGroups: (params: Record<string, unknown> = {}) => callOp("listSessionGroups", params),
        listSessions: (params: Record<string, unknown> = {}) => callOp("listSessions", params),
        listSessionShares: (params: Record<string, unknown> = {}) => callOp("listSessionShares", params),
        listSessionsPage: (params: Record<string, unknown> = {}) => callOp("listSessionsPage", params),
        listSignalEndpoints: (params: Record<string, unknown> = {}) => callOp("listSignalEndpoints", params),
        listWebhookBindings: (params: Record<string, unknown> = {}) => callOp("listWebhookBindings", params),
        listWebhookConnectors: (params: Record<string, unknown> = {}) => callOp("listWebhookConnectors", params),
        listWebhookReceipts: (params: Record<string, unknown> = {}) => callOp("listWebhookReceipts", params),
        listWebhookSessionTemplates: (params: Record<string, unknown> = {}) => callOp("listWebhookSessionTemplates", params),
        listWorkers: (params: Record<string, unknown> = {}) => callOp("listWorkers", params),
        moveSessionsToGroup: (params: Record<string, unknown> = {}) => callOp("moveSessionsToGroup", params),
        pinAgentPackageVersion: (params: Record<string, unknown> = {}) => callOp("pinAgentPackageVersion", params),
        placeSessionsInGroup: (params: Record<string, unknown> = {}) => callOp("placeSessionsInGroup", params),
        pruneDeletedSummaries: (params: Record<string, unknown> = {}) => callOp("pruneDeletedSummaries", params),
        raiseSignal: (params: Record<string, unknown> = {}) => callOp("raiseSignal", params),
        readArtifactBase64: (params: Record<string, unknown> = {}) => callOp("readArtifactBase64", params),
        readCanvasKv: (params: Record<string, unknown> = {}) => callOp("readCanvasKv", params),
        readFacts: (params: Record<string, unknown> = {}) => callOp("readFacts", params),
        regenerateSession: (params: Record<string, unknown> = {}) => callOp("regenerateSession", params),
        removeCanvasShareLink: (params: Record<string, unknown> = {}) => callOp("removeCanvasShareLink", params),
        removeProviderLimit: (params: Record<string, unknown> = {}) => callOp("removeProviderLimit", params),
        renameSession: (params: Record<string, unknown> = {}) => callOp("renameSession", params),
        replayWebhookReceipt: (params: Record<string, unknown> = {}) => callOp("replayWebhookReceipt", params),
        republishAgentPackageVersion: (params: Record<string, unknown> = {}) => callOp("republishAgentPackageVersion", params),
        resetCanvasShareLink: (params: Record<string, unknown> = {}) => callOp("resetCanvasShareLink", params),
        resetClusterFeatureFlag: (params: Record<string, unknown> = {}) => callOp("resetClusterFeatureFlag", params),
        restartSystemSession: (params: Record<string, unknown> = {}) => callOp("restartSystemSession", params),
        revokeAgentPackageEditor: (params: Record<string, unknown> = {}) => callOp("revokeAgentPackageEditor", params),
        revokeSessionShare: (params: Record<string, unknown> = {}) => callOp("revokeSessionShare", params),
        revokeSignalEndpoint: (params: Record<string, unknown> = {}) => callOp("revokeSignalEndpoint", params),
        revokeWebhookBinding: (params: Record<string, unknown> = {}) => callOp("revokeWebhookBinding", params),
        revokeWebhookConnector: (params: Record<string, unknown> = {}) => callOp("revokeWebhookConnector", params),
        revokeWebhookSessionTemplate: (params: Record<string, unknown> = {}) => callOp("revokeWebhookSessionTemplate", params),
        searchFacts: (params: Record<string, unknown> = {}) => callOp("searchFacts", params),
        searchGraphEdges: (params: Record<string, unknown> = {}) => callOp("searchGraphEdges", params),
        searchGraphNodes: (params: Record<string, unknown> = {}) => callOp("searchGraphNodes", params),
        sendAnswer: (params: Record<string, unknown> = {}) => callOp("sendAnswer", params),
        sendMessage: (params: Record<string, unknown> = {}) => callOp("sendMessage", params),
        sendSessionEvent: (params: Record<string, unknown> = {}) => callOp("sendSessionEvent", params),
        setAgentPackageEnabled: (params: Record<string, unknown> = {}) => callOp("setAgentPackageEnabled", params),
        setAgentPackageScope: (params: Record<string, unknown> = {}) => callOp("setAgentPackageScope", params),
        setArtifactPinned: (params: Record<string, unknown> = {}) => callOp("setArtifactPinned", params),
        setCanvasKvAccess: (params: Record<string, unknown> = {}) => callOp("setCanvasKvAccess", params),
        setClusterDefault: (params: Record<string, unknown> = {}) => callOp("setClusterDefault", params),
        setClusterFeatureFlag: (params: Record<string, unknown> = {}) => callOp("setClusterFeatureFlag", params),
        setCurrentUserGitHubCopilotKey: (params: Record<string, unknown> = {}) => callOp("setCurrentUserGitHubCopilotKey", params),
        setCurrentUserProfileSettings: (params: Record<string, unknown> = {}) => callOp("setCurrentUserProfileSettings", params),
        setModelDefault: (params: Record<string, unknown> = {}) => callOp("setModelDefault", params),
        setMyDefault: (params: Record<string, unknown> = {}) => callOp("setMyDefault", params),
        setMyFeatureFlag: (params: Record<string, unknown> = {}) => callOp("setMyFeatureFlag", params),
        setProviderAllowance: (params: Record<string, unknown> = {}) => callOp("setProviderAllowance", params),
        setProviderHold: (params: Record<string, unknown> = {}) => callOp("setProviderHold", params),
        setProviderLimit: (params: Record<string, unknown> = {}) => callOp("setProviderLimit", params),
        setProviderSystemUse: (params: Record<string, unknown> = {}) => callOp("setProviderSystemUse", params),
        setSessionModel: (params: Record<string, unknown> = {}) => callOp("setSessionModel", params),
        setSessionVisibility: (params: Record<string, unknown> = {}) => callOp("setSessionVisibility", params),
        setSystemGitHubCopilotKey: (params: Record<string, unknown> = {}) => callOp("setSystemGitHubCopilotKey", params),
        setSystemModelDefault: (params: Record<string, unknown> = {}) => callOp("setSystemModelDefault", params),
        setSystemSessionModel: (params: Record<string, unknown> = {}) => callOp("setSystemSessionModel", params),
        setUserFeatureFlag: (params: Record<string, unknown> = {}) => callOp("setUserFeatureFlag", params),
        similarFacts: (params: Record<string, unknown> = {}) => callOp("similarFacts", params),
        startFactsEmbedder: (params: Record<string, unknown> = {}) => callOp("startFactsEmbedder", params),
        stopFactsEmbedder: (params: Record<string, unknown> = {}) => callOp("stopFactsEmbedder", params),
        stopSessionTurn: (params: Record<string, unknown> = {}) => callOp("stopSessionTurn", params),
        storeFact: (params: Record<string, unknown> = {}) => callOp("storeFact", params),
        testWebhookBinding: (params: Record<string, unknown> = {}) => callOp("testWebhookBinding", params),
        unsetMyFeatureFlag: (params: Record<string, unknown> = {}) => callOp("unsetMyFeatureFlag", params),
        unsetUserFeatureFlag: (params: Record<string, unknown> = {}) => callOp("unsetUserFeatureFlag", params),
        updateMyProviderCredential: (params: Record<string, unknown> = {}) => callOp("updateMyProviderCredential", params),
        updateSessionGroup: (params: Record<string, unknown> = {}) => callOp("updateSessionGroup", params),
        updateSharedProviderCredential: (params: Record<string, unknown> = {}) => callOp("updateSharedProviderCredential", params),
        updateWebhookBinding: (params: Record<string, unknown> = {}) => callOp("updateWebhookBinding", params),
        updateWebhookConnector: (params: Record<string, unknown> = {}) => callOp("updateWebhookConnector", params),
        updateWebhookRetentionPolicy: (params: Record<string, unknown> = {}) => callOp("updateWebhookRetentionPolicy", params),
        updateWebhookSessionTemplate: (params: Record<string, unknown> = {}) => callOp("updateWebhookSessionTemplate", params),
        uploadAgentPackage: (params: Record<string, unknown> = {}) => callOp("uploadAgentPackage", params),
        uploadArtifact: (params: Record<string, unknown> = {}) => callOp("uploadArtifact", params),
        upsertGraphEdge: (params: Record<string, unknown> = {}) => callOp("upsertGraphEdge", params),
        upsertGraphNamespace: (params: Record<string, unknown> = {}) => callOp("upsertGraphNamespace", params),
        upsertGraphNode: (params: Record<string, unknown> = {}) => callOp("upsertGraphNode", params),
        waitForStatusChange: (params: Record<string, unknown> = {}) => callOp("waitForStatusChange", params),
        writeCanvasKv: (params: Record<string, unknown> = {}) => callOp("writeCanvasKv", params),
    };
}
